name: Support
description: File a support ticket to raise a question you have or a problem you're encountering.
title: "[Support]: "
labels: ["support"]
body:
- type: textarea
  id: problem
  attributes:
    label: Problem
    description:  Provide a clear and concise description of what the problem is or what question you have, including the associated pipeline id and the impacted pipeline activities if possible.
    placeholder: I noticed an error with pipeline run id "9cf47678-e546-11ed-9b86-00155d9996ff" at the "validation_if" activity. The validation failed due to missing information in the 'City' field despite it being an optional field.
  validations:
    required: true
- type: textarea
  id: impact
  attributes:
    label: Impact
    description: If applicable, describe the impact this problem is causing to your program or organization.
    placeholder: This error impacts ~30% of eCR messages.  
  validations:
    required: false
 - type: textarea
attributes:
  label: Steps To Reproduce
  description: List steps to reproduce the behavior.
  placeholder: |
    1. In this environment...
    2. With this config...
    3. Run '...'
    4. See error... 
  - type: textarea
  id: intended-outcome
  attributes:
    label: Intended outcome
    description: Describe a clear and concise description of what you expected to happen.
    placeholder: I expected the eCR message to successfully pass validation despite not having information in the "City" field.
  validations:
    required: false
- type: textarea
attributes:
  label: desktop
  description: |
    examples:
      - **OS**: Ubuntu 20.04
      - **Node**: 13.14.0
      - **npm**: 7.6.3
  value: |
      - OS:
      - Node:
      - npm:
  render: markdown
validations:
  required: false 
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
      Note: Do NOT include any screenshots or information containing PII. 
    required: false
